Blog/urls.py
from django.urls import path,include
from apps.articles import views
from django.views import static
from django.conf import settings
from django.conf.urls import url



urlpatterns = [
    path('',views.index,name='index' ),
    path('about',views.aboutme,name='aboutme'),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.blogauth.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
    path('articles/', include('apps.articles.urls')),
    path('date/<int:year>/<int:month>/<int:day>/',views.timecate,name='date'),
    url(r'^static/(?P<path>.*)$', static.serve,{'document_root': settings.STATIC_ROOT}, name='static'),
]

apps/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('list/',views.articles_list,name='articles_list'),
    path('<int:articles_id>/',views.articles_detail,name='articles_detail'),
    path('comment/',views.comment,name = 'comment'),
]

apps/blogauth/urls.py
from django.urls import path
from . import views

app_name = 'blogauth'

urlpatterns = [
    path('login/',views.login_view,name = 'login'),
    path('logout/',views.logout_view,name = 'logout'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('register/',views.register,name='register'),
    path('sms_captcha/',views.sms_captcha,name='sms_captcha'),
]

apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('',views.index,name='index'),
    path('articles_category/',views.articles_category,name='articles_category'),
    path('add_articles_category/',views.add_articles_category,name='add_articles_category'),
    path('delete_articles_category/',views.delete_articles_category,name='delete_articles_category'),
    path('edit_articles_category/',views.edit_articles_category,name='edit_articles_category'),
    path('write_articles/', views.WriteArticles.as_view(),name='write_articles'),
    path('articles_list/', views.ArticlesListView.as_view(),name='articles_list'),
    path('edit_articles/', views.EditArticlesView.as_view(),name='edit_articles'),
    path('delete_articles/', views.delete_articles,name='delete_articles'),
]

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
from apps.forms import FormMixin
from django import forms
from apps.articles.models import Articles

class EditArticlesCategoryForm(forms.Form):
    pk = forms.IntegerField(error_messages={"required":"必须传入分类的id！"})
    name = forms.CharField(max_length=100)


class WriteArticlesForm(forms.ModelForm,FormMixin):
    category = forms.IntegerField()
    class Meta:
        model = Articles
        exclude =['category','author','pub_time']
        error_messages ={
            'title':{"required":"请输入标题"},
            'desc':{"required":"请输入描述"},
            'content':{"required":"请输入内容"},
        }

class EditArticlesForm(forms.ModelForm,FormMixin):
    category = forms.IntegerField()
    pk = forms.IntegerField()
    class Meta:
        model = Articles
        exclude = ['category','author','pub_time']
        error_messages = {
            'title': {"required": "请输入标题"},
            'desc': {"required": "请输入描述"},
            'content': {"required": "请输入内容"},
        }

apps/cms/views.py
from django.shortcuts import render
from django.views import View
from django.views.decorators.http import require_POST,require_GET
from apps.articles.models import ArticlesCategory,Articles
from utils import restful
from .forms import EditArticlesCategoryForm,WriteArticlesForm,EditArticlesForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from datetime import datetime
from django.utils.timezone import make_aware
from urllib import parse
from django.db.models.aggregates import Count
from apps.blogauth.decorators import superuser_required
from django.utils.decorators import method_decorator


@superuser_required
def index(request):
    return render(request,'cms/index.html')

# 文章发布
@method_decorator(superuser_required, name='dispatch')
class WriteArticles(View):
    def get(self,request):
        categories = ArticlesCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request,'cms/write_articles.html',context=context)

    def post(self,request):
        form = WriteArticlesForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = ArticlesCategory.objects.get(pk=category_id)
            Articles.objects.create(title=title, desc=desc, content=content, category=category,
                                author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())



# 文章分类
@superuser_required
@require_GET
def articles_category(request):
    category_list = ArticlesCategory.objects.annotate(num_category=Count('articles'))# 注意Count中是关联模型的小写

    context = {
        'category_list':category_list,
    }
    return render(request,'cms/articles_category.html',context=context)

# 添加分类
@superuser_required
@require_POST
def add_articles_category(request):
    name = request.POST.get('name')
    exists = ArticlesCategory.objects.filter(name=name).exists()
    if not exists:
        ArticlesCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已经存在！')
# 更改分类
@superuser_required
@require_POST
def edit_articles_category(request):
    form = EditArticlesCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            ArticlesCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='该分类不存在！')
    else:
        return restful.params_error(message=form.get_error())

@superuser_required
# 删除分类
@require_POST
def delete_articles_category(request):
    form = EditArticlesCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        try:
            ArticlesCategory.objects.filter(pk=pk).delete()
            return restful.ok()
        except:
            return restful.params_error(message='该分类不存在！')
    else:
        return restful.params_error(message=form.get_error())

# 文章列表
@method_decorator(superuser_required, name='dispatch')
class ArticlesListView(View):

    def get(self,request):
        # request.GET：获取出来的所有数据，都是字符串类型
        page = int(request.GET.get('p', 1))
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0) or 0)
        articles = Articles.objects.select_related('category', 'author').all()

        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')
            else:
                start_date = datetime(year=2020, month=1, day=1)
            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.today()
            articles = articles.filter(pub_time__range=((start_date), (end_date)))

        if title:
            articles = articles.filter(title__icontains=title)

        if category_id:
            articles = articles.filter(category=category_id)

        paginator = Paginator(articles, 2)
        page_obj = paginator.page(page)
        context_data = self.get_pagination_data(paginator, page_obj)

        context={
            'categories': ArticlesCategory.objects.all(),
            'articles':page_obj.object_list,
            'page_obj': page_obj,
            'paginator': paginator,
            'category_id': category_id,
            'start': start,
            'end': end,
            'title': title,
            'url_query':'&'+parse.urlencode(
                {
                    'start': start or '',
                    'end': end or '',
                    'title': title or '',
                    'category': category_id or ''
                }
            )
        }

        context.update(context_data)
        return render(request, 'cms/articles_list.html',context= context)

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            # left_pages：代表的是当前这页的左边的页的页码
            'left_pages': left_pages,
            # right_pages：代表的是当前这页的右边的页的页码
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages
        }

# 删除文章

@require_POST
def delete_articles(request):
    articles_id = request.POST.get('articles_id')
    Articles.objects.filter(pk=articles_id).delete()
    return restful.ok()

# 编辑文章
@method_decorator(superuser_required, name='dispatch')
class EditArticlesView(View):
    def get(self,request):
        articles_id = request.GET.get('articles_id')
        articles = Articles.objects.get(pk=articles_id)
        context = {
            'articles': articles,
            'categories': ArticlesCategory.objects.all()
        }
        return render(request,'cms/write_articles.html',context=context)

    def post(self, request):
        form = EditArticlesForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            pk = form.cleaned_data.get("pk")
            category = ArticlesCategory.objects.get(pk=category_id)
            Articles.objects.filter(pk=pk).update(title=title, desc=desc, content=content,
                                              category=category)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())

front/templates/cms/articles_category.html
{% extends 'cms/base.html' %}

{% block title %}
    文章分类
{% endblock %}

{% block head %}
    <script src="{% static 'js/articles_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>文章分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button class="btn btn-primary pull-right" id="add-btn">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>分类名称</th>
                                <th>文章数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for category in category_list %}
                                <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                    <td>{{ category.name }}</td>
                                    <td>{{ category.num_category }}</td>
                                    <td>
                                        <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                        <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/articles_list.html
{% extends 'cms/base.html' %}
{% load articles_filters %}

{% block title %}
    新闻列表
{% endblock %}

{% block head %}
    <style>
    .left-group{
        margin-right: 40px;
    }
    </style>
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/articles_list.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>文章列表管理</h1>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <form action="" method="get" class="form-inline">
                <div class="form-group left-group">
                    <label for="">时间：</label>
                    {% if start %}
                        <input type="text" class="form-control" name="start" placeholder="起始时间" id="start-picker" readonly value="{{ start }}">
                    {% else %}
                        <input type="text" class="form-control" name="start" placeholder="起始时间" id="start-picker" readonly>
                    {% endif %}
                    <span>—</span>
                    {% if end %}
                        <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间" readonly value="{{ end }}">
                    {% else %}
                        <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间" readonly>
                    {% endif %}
                </div>
                <div class="form-group left-group">
                    <label for="title-input">标题：</label>
                        {% if title %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字" value="{{ title }}">
                    {% else %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字">
                    {% endif %}
                </div>
                <div class="form-group left-group">
                    <label for="category-input">分类：</label>
                    <select name="category" id="" class="form-control">
                        {% if category_id == 0 %}
                            <option value="0" selected>所有分类</option>
                        {% else %}
                            <option value="0">所有分类</option>
                        {% endif %}
                        {% for category in categories %}
                            {% if category_id == category.pk %}
                                <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                            {% else %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group left-group">
                    <button class="btn btn-primary">查询</button>
                </div>
                <div class="form-group">
                    <a href="{% url 'cms:articles_list' %}">清除查询</a>
                </div>
            </form>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>标题</th>
                        <th>分类</th>
                        <th>发布时间</th>
                        <th>作者</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for article in articles %}
                        <tr>
                            <td><a target="_blank" href="{% url 'articles:articles_detail' articles_id=article.pk %}">{{ article.title }}</a></td>
                            <td>{{ article.category.name }}</td>
                            <td>{{ article.pub_time|time_format }}</td>
                            <td>{{ article.author.username }}</td>
                            <td>
                                <a href="{% url 'cms:edit_articles' %}?articles_id={{ article.pk }}" class="btn btn-info btn-xs">编辑</a>
                                <button class="btn btn-danger btn-xs delete-btn" data-articles-id="{{ article.pk }}">删除</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="box-footer">
            <p class="pull-left">第{{ current_page }}/总共{{ num_pages }}页</p>
            <ul class="pagination pull-right">
                {#上一页#}
                {% if page_obj.has_previous %}
                    <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                {% endif %}
                {# 是否需要出现三个点 #}
                {% if left_has_more %}
                    <li><a href="?p=1">1</a></li>
                    <li><a href="javascript:void(0);">...</a></li>
                {% endif %}

                {# 左边的页码 #}
                {% for left_page in left_pages %}
                    <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                {% endfor %}

                {# 当前的页面 #}
                <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                {# 右边的页码 #}
                {% for right_page in right_pages %}
                    <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                {% endfor %}

                {# 用来控制右边三个点 #}
                {% if right_has_more %}
                    <li><a href="javascript:void(0);">...</a></li>
                    <li><a href="?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                {% endif %}
                {#下一页#}
                {% if page_obj.has_next %}
                    <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                {% else %}
                    <li class="disabled"><a href="#">下一页</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
</div>
{% endblock %}

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}{% endblock %} | 博客管理系统</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">

  <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
  <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
  <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
  <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
  <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
  <script src="{% static 'js/blogajax.min.js' %}"></script>
  <script src="{% static 'js/blogalert.min.js' %}"></script>
  <script src="{% static 'js/message.min.js' %}"></script>


  {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>CMS</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>博客后台管理系统</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="http://cdn.azuzu.cn/1587374637406.png" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="http://cdn.azuzu.cn/1587374637406.png" class="img-circle" alt="User Image">

                <p>
                  {{ user.username }}
                  <small>python小白</small>
                </p>
              </li>
              <!-- Menu Body -->

              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">个人中心</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'blogauth:logout' %}" class="btn btn-default btn-flat">退出登录</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- search form -->

      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
          <li >
              <a href="{% url 'cms:index' %}">
                  <i class="fa fa-home"></i>
                  <span>首页</span>
              </a>
          </li>
          <li class="header">文章管理</li>
          <li>
              <a href="{% url 'cms:articles_list' %}">
                  <i class="fa fa-list"></i>
                  <span>文章列表</span>
              </a>
          </li>
          <li>
              <a href="{% url 'cms:write_articles' %}">
                  <i class="fa fa-edit"></i>
                  <span>发布文章</span>
              </a>
          </li>
          <li>
              <a href="{% url 'cms:articles_category' %}">
                  <i class="fa fa-tag"></i>
                  <span>文章分类</span>
              </a>
          </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <div class="content-wrapper">
    <section class="content-header">
        {% block content-header %}
        
        {% endblock %}
    </section>

    <section class="content">
        {% block content %}
        
        {% endblock %}
    </section>
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    Copyright © 2014-2016 Almsaeed Studio. All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}
    首页
{% endblock %}

{% block content-header %}
    <h1>欢迎来到CMS管理系统</h1>
{% endblock %}

front/templates/cms/write_articles.html
{% extends 'cms/base.html' %}

{% block title %}
    {% if articles %}
        编辑文章
    {% else %}
        发布文章
    {% endif %}
{% endblock %}

{% block head %}
    <script src="https://unpkg.com/qiniu-js@2.4.0/dist/qiniu.min.js"></script>
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script src="{% static 'js/write_articles.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>
    {% if articles %}
        编辑文章
    {% else %}
        发布文章
    {% endif %}
    </h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <form action="" class="form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="title-form">标题</label>
                            {% if articles %}
                                <input type="text" class="form-control" name="title" id="title-form" value="{{ articles.title }}">
                            {% else %}
                                <input type="text" class="form-control" name="title" id="title-form">
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="category-form">分类</label>
                            <select name="category" id="category-form" class="form-control">
                                {% for category in categories %}
                                    {% if articles and articles.category_id == category.pk %}
                                        <option value="{{ category.pk }}" >{{ category.name }}</option>
                                    {% else %}
                                        <option value="{{ category.pk }}" >{{ category.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="desc-form">描述</label>
                            {% if articles %}
                                <input type="text" class="form-control" id="desc-form" name="desc" value="{{ articles.desc }}">
                            {% else %}
                                <input type="text" class="form-control" id="desc-form" name="desc">
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="content-form">内容</label>
                            <script id="editor" type="text/plain">{{ articles.content|safe }}</script>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button id="submit-btn" data-articles-id="{{ articles.pk }}" class="btn btn-primary pull-right">发布文章</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}