Blog/urls.py
from django.urls import path,include
from apps.articles import views
from django.views import static
from django.conf import settings
from django.conf.urls import url



urlpatterns = [
    path('',views.index,name='index' ),
    path('about',views.aboutme,name='aboutme'),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.blogauth.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
    path('articles/', include('apps.articles.urls')),
    path('date/<int:year>/<int:month>/<int:day>/',views.timecate,name='date'),
    url(r'^static/(?P<path>.*)$', static.serve,{'document_root': settings.STATIC_ROOT}, name='static'),
]

apps/blogauth/urls.py
from django.urls import path
from . import views

app_name = 'blogauth'

urlpatterns = [
    path('login/',views.login_view,name = 'login'),
    path('logout/',views.logout_view,name = 'logout'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('register/',views.register,name='register'),
    path('sms_captcha/',views.sms_captcha,name='sms_captcha'),
]

apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('',views.index,name='index'),
    path('articles_category/',views.articles_category,name='articles_category'),
    path('add_articles_category/',views.add_articles_category,name='add_articles_category'),
    path('delete_articles_category/',views.delete_articles_category,name='delete_articles_category'),
    path('edit_articles_category/',views.edit_articles_category,name='edit_articles_category'),
    path('write_articles/', views.WriteArticles.as_view(),name='write_articles'),
    path('articles_list/', views.ArticlesListView.as_view(),name='articles_list'),
    path('edit_articles/', views.EditArticlesView.as_view(),name='edit_articles'),
    path('delete_articles/', views.delete_articles,name='delete_articles'),
]

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1702998_axrec4ul63u.css">
    <link rel="stylesheet" href="{% static 'css/auth.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/blogajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo-box">
                <a href="/"></a>
            </div>

            <ul class="nav">
                {% block nav %}
                {% endblock %}
            </ul>

            <div class="auth-box">
                <i class="icon-person iconfont"></i>
                {% if user.is_authenticated %}
                    <a href="#" class="authenticated-box">{{ user.username }}</a>
                    <div class="user-more-box">
                        <i class="triangle"></i>
                        {% if user.is_staff %}
                        <a href="{% url 'cms:index' %}">管理系统</a>
                        {% endif %}
                        <a href="{% url 'blogauth:logout' %}">退出登录</a>
                    </div>
                {% else %}
                    <a href="#" class="signin-btn">登录</a> /
                    <a href="#" class="signup-btn">注册</a>
                {% endif %}
            </div>
        </div>
    </header>
    {% block main %}
    {% endblock %}
    <footer class="footer">
        <!--
        <div class="top-group">
            <div class="site-info">
			<span>友情链接：</span>
						<a href="#" >博客</a>
						<a href="#" >Lara博客</a>
						<a href="#" target=&quot;_blank&quot;>窝心美文</a>
					</div>
        </div>-->

        <div class="bottom-group">
            闽ICP备20005702号
        </div>
    </footer>
<div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-wrapper">
                    <div class="signin-group auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                            </div>
                             <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <label class="remember-label">
                                    <input type="checkbox" name="remember" value="1">
                                    记住我
                                </label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即登录">
                            </div>
                        </div>
                    </div>
                    <div class="signup-group auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" id="img-captcha" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="{% url 'blogauth:img_captcha' %}" alt="" class="img-captcha" style="cursor:pointer;">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password2" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码功能未开通，无需输入">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即注册">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>